### ISSUE TITLE
World and Server names is not set

### ISSUE THREAD

**Issue by TerZer** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#1]
I cloned this docker container, build it and then I started this container with `docker_run.sh` skript. After everything was done it showed me this:
https://i.gyazo.com/03cf63583bdce3c3e6f7e46d10c8c487.png

**Comment by Lazalatin** [comment]
Hi @TerZer! 
First of all I really appreciate your contribution by opening this issue here. Thank you!

Currently this docker image has some loose ends and up until now I did not manage to make it fully usable without taking advantage of the world creation provided by the GUI, which I needed a genuine windows OS for.

Additionally this repository does not hold the actual progress of the image, as I was too lazy to provide a fully documented way to do use it and to push my latest progress to it.

I'd like to keep this issue open to inform you of my progress. I will update this repository in the next 24h and provide a more documenting README.md regarding on how to use the image properly.

**Comment by TerZer** [comment]
@Lazalatin Thank you for looking into this case and for quick deadline for fix! 👍 I will try running it and tell you about my results.

**Comment by TerZer** [comment]
I tried running server using docker_v1 branch and got same results. :(

**Comment by Lazalatin** [comment]
Hi TerZer. I added more information to the README.md of the project. Now master and docker_v1 should be the same so the actual progress is transparent.

Regarding the title of the issue: Having no World Name to be shown normally results from not having used the correct path to the to-be-loaded world data, or from trying to generate a new world. The latter is not possible with this image until now. I opened a new issue for this case #2 

I hope this helps you to successfully start your own server using this image :)

**Comment by TerZer** [comment]
Thanks @Lazalatin ! But can I get more information on how and where I should put world file and what exactly to change? (I am fresh on docker and stuff like that)

**Comment by Lazalatin** [comment]
Well, presumably you have generated the new world using the gui according to your needs, the only thing you have to do is to copy the `SpaceEngineersDedicated` directory as described in the [README.md](..) to a place on your machine. (i.e. `/opt/SpaceEngineersDedicated`)

Then you adjust at least the environment variables `SERVER_NAME` and `WORLD_NAME` to your liking in the `docker-compose.yml` file. If you experience problems with starting the file using `docker-compose up` you may change the version property of the file to `'2'`, which should also do the job.

**Comment by TerZer** [comment]
Hmm.. I generated world name `SOGA-System`. I copied that folder to `/opt/SpaceEngineersDedicated` then in `docker-compose.yml` I changed `WORLD_NAME` variable to `SOGA-System` and ran `docker-compose up` and I got same results. Server could not find world.

**Comment by Lazalatin** [comment]
So let us try to do this step by step. :+1: 

First, have a look into `/opt/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg` Look at the paths in the tags `<LoadWorld>` and `<PremadeCheckpointPath>`, do they look correct? Maybe post them here.

Here the tags from my setting (Yours should be similar):
```
<LoadWorld>C:\users\root\AppData\Roaming\SpaceEngineersDedicated\Saves\YourWorldName</LoadWorld>
...
<PremadeCheckpointPath>C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineersDedicatedServer\Content\CustomWorlds\Alien Planet</PremadeCheckpointPath>
```

Hence I have `YourWorldName` in my path, there should no necessity for the path to match the `<WorldName>` tag in the configuration. I tried it, does work nevertheless.

Another thing that pops into my mind right now: Did you start the server once after generating it using the GUI? Some threads at reddit suppose this could be necessary.

**Comment by TerZer** [comment]
`/opt/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg` looks like this:
https://pastebin.com/gsFegzmX

`/opt/SpaceEngineersDedicated` folder looks like this:
https://gyazo.com/1bf8d58ddb2b4d09c3050e33f6d75410

`docker-compose.yml` looks like this:
https://pastebin.com/WXUdnxf8

I ran the server on windows, it created world successfully.

**Comment by Lazalatin** [comment]
First thing I noticed:
- Your configuration file says, your server data is at `C:\users\root\AppData\Roaming\SpaceEngineersDedicated\Saves\SOGA-System` but according to your directory screenshot it is just right at: `/opt/SpaceEngineersDedicated` which is mounted to `C:\users\root\AppData\Roaming\SpaceEngineersDedicated`.

So you have to move your `SOGA-System` directory into the `Saves` directory in order to work correctly. Try moving the world directory and try starting the server again.

**Comment by TerZer** [comment]
Okey, so I put `SOGA-System` folder in `Saves` directory and same thing: world is unable to load. Maybe my world does not have some files?
https://gyazo.com/034ebfc2107d8fe7018bccaf05426270

**Comment by Lazalatin** [comment]
Looks alright to me, could you paste the log of the docker container here directly?

**Comment by TerZer** [comment]
I could not find docker log file so I can provide you with SE server log: https://pastebin.com/NA266SAF

**Comment by Lazalatin** [comment]
As your server log shows, I made a mistake in the `sed` expression in the `entrypoint.sh` file. The most recent version of the `master` branch should solve that. You may need to delete the config file beforehand to restarting the container.

**Comment by TerZer** [comment]
All seems to work now! Thanks! But I get some weird messages like: https://gyazo.com/cad4a5f98766cd03c30f97dba467c316
And then I join the server it's laggy and it's unable to play (only several fps). I use VPS to run this with these specs:
8 x 3 GHz vCPUs
24576 MB RAM
and Debian 9 OS
So I assume that I have resourses for powering the server but something is wrong with that RAM allocation.

**Comment by Lazalatin** [comment]
This is an issue not related to the one we tried to solve here. As this would require much more investigation I would like you to open a new issue for it. But I am happy it runs now :+1: 

If opening the new issue please provide more information about the system, like your docker and docker-compose version.
