### ISSUE TITLE
Service 'space' failed to build:

### ISSUE THREAD

**Issue by Welzfisch** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#10]
I am starting the Container by docker-composer up from my console. Any help here? (Sry if this mighty be a noobish question, hardly ever worked with Docker though :/ (Docker-ce and Docker Composer where updated)
Error is:

The command '/bin/sh -c dpkg --add-architecture i386 &&     wget -nc https://dl.winehq.org/wine-builds/winehq.key &&     apt-key add winehq.key && rm winehq.key &&     add-apt-repository https://dl.winehq.org/wine-builds/ubuntu/ &&     add-apt-repository ppa:cybermax-dexter/sdl2-backport &&     apt-get -q update &&     apt-get --no-install-recommends --no-install-suggests -y install         winehq-devel wine-devel wine-devel-i386 wine-devel-amd64         &&     rm -rf /root/.wine &&     env WINEDLLOVERRIDES="mscoree,mshtml=" wineboot --init &&     xvfb-run winetricks --unattended vcrun2013 vcrun2017 &&     wineboot --init &&     winetricks --unattended dotnet472 corefonts dxvk &&     apt-get clean autoclean && apt-get autoremove -y && rm -rf /var/lib/{apt,dpkg,cache,log}/' returned a non-zero code: 1

**Comment by Welzfisch** [comment]
I needed to install a gui for my server and connected with x11 enabled in putty. That worked for me.

**Comment by Lazalatin** [comment]
Hi @Welzfisch, sorryforthe late reply.

actually you should not need to install x11, as this is a purely console based build. Maybe you can provide the specific versions of docker(-compose) you are using. I will try to investigate it, as stated in #11 :)
