### ISSUE TITLE
Preloader warning

### ISSUE THREAD

**Issue by TerZer** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#3]
I set my server up on fresh host. After I started server it shows me these strange warnings:
https://gyazo.com/31e49c9257c6f7ff5d2f738b53898e99
And then I join the server it's laggy and it's unable to play (only several fps). I use VPS to run this with these specs:
8 vCPU
24 GB
and Ubuntu 18 OS 64 bit
So I assume that I have resourses for powering the server but something is wrong here.
After I searched in google for this particular thing, I found that it has something to do with `wine`.

**Comment by Lazalatin** [comment]
So let me get this straight. This seems not to be a problem with the particular image this project grants. Hence the `wontfix` label here.

But for me it is also of relevance to make this image as widely available as possible. As I personally host this on a dedicated host, without virtualization, this seems to be something worthy to investigate in.

@TerZer You need to provide more information:
* Which hosting service are you using?
* From which sites and discussions have you gotten the info from that this may be a wine issue? It seems to be working fine on my self-assembled home-server.

For me it seems that we have to investigate any relations between virtualized server environments and running containers with wine on them.

**Comment by TerZer** [comment]
I am using `hostinger.lt`, to be exact this plan:
https://gyazo.com/20c08e1888d32dbd2947a4bac3ef2917
I used google and searched for `preloader: Warning: failed to reserve range 0000000000010000-0000000000110000`:
https://gyazo.com/74bce8760346b588453180d51a741f94

**Comment by Lazalatin** [comment]
As this question is momentarily topic at the Space Engineers® official Discord® Server and I would like to keep record of the ongoing discussion I briefly describe what has been thought through so far.

A first suggestion from the user `Onyx` was, that this particular problem can be experienced in a virtualized server environment, where the kernel does not allow memory allocation in certain ranges. To overcome this one should check if the `vm.mmap_min_addr` kernel setting is enforced somewhere about the system running the container. Sadly until now, no one was able to check of this is true. In case of @TerZer the hosting provider seems not to be willing or able to omit this security feature.

I will add more information here, as it is getting to my ears or eyes.

**Comment by Lazalatin** [comment]
As this conversation went on where I could not follow it, this issue is closed until further notice ;-)
