### ISSUE TITLE
ERROR: Service 'space' failed to build: Error parsing reference: "ubuntu:18.04 as preStage" is not a valid repository/tag: invalid reference format

### ISSUE THREAD

**Issue by Hoborific** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#4]
docker-compose version 1.18.0, build 8dd22a9

Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-103.git7f2769b.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7f2769b/1.13.1
 Built:           Sun Sep 15 14:06:47 2019
 OS/Arch:         linux/amd64
 Experimental:    false

**Comment by Lazalatin** [comment]
It seems that your docker version is far too old to support multistage builds. Please use at least docker version v17.05 as described here: https://docs.docker.com/develop/develop-images/multistage-build/

Furthermore, if you are not able to upgrade to a recent docker version, you may also consider using a recent podman version.

Please seek advice from the centOS community on how to do so.
