### ISSUE TITLE
Server config does not reflect what the server is actually running

### ISSUE THREAD

**Issue by Torkiwi** [Lazalatin/space-engineers-dedicated-ubuntu-docker-server#5]
Been playing  with SpaceEngineers-Dedicated.cfg ( both in ./resources and the one in /opt/SpaceEngineersDedicated )

Some options seems to be ignored on server reboot : 

-  <GameMode>Survival</GameMode>
 Server stays on Creative

Is there a 3rd cfg files hidden somewhere?
Do I need to do something special for a server reboot ( more than simply  $ sudo docker-compose up ? )

**Comment by Torkiwi** [comment]
Small update on what i've figured out :

The files : 
-   **Sandbox_config.sbc** ( /opt/SpaceEngineersDedicated/Saves/MyServer )

-  **Sandbox.sbc**  ( /opt/SpaceEngineersDedicated/Saves/MyServer )

are the one with the "real" config. This has to do with how SE manages dedicated server config.

The most important one is **Sandbox.sbc**, but in some cases, it will load from the other file.


The weird part : 
-  Adding admins through /opt/SpaceEngineersDedicated/SpaceEngineers-Dedicated.cfg
works, so some of the config is shared between all the config files.

**Comment by Lazalatin** [comment]
Hi @Torkiwi and thank you for opening this well created issue! :100: 

First of all: You are right with your observations.

The server loads all the options in the subtags of the tag `<SessionSettings />` not from the [server configuration file](https://github.com/Lazalatin/space-engineers-dedicated-ubuntu-docker-server/blob/master/resources/SpaceEngineers-Dedicated.cfg) but from the very `Sandbox_config.sbc` in the actually saved world data. Therefore this part of the config may be changed but is ignored.

This behavior is intended, as I do not want to irreversibly destroy or override any options a user has picked when the world was generated. This behavior can be toggled by removing the `-ignorelastsession` parameter from the last line of the [entrypoint.sh](https://github.com/Lazalatin/space-engineers-dedicated-ubuntu-docker-server/blob/master/entrypoint.sh) and rebuilding the image.

In future this option should be made toggable by the `docker-compose.yml`. As such, I will treat this issue as a feature request.

As a quick fix for your problem I suggest that you make changes to your worlds options (like the `<GameMode />`) in the `Sandbox_config.sbc` you found and restart the server.

If you encounter any connecting observations, please let me know. And as always, if you encounter anything else, feel free to open another issue :+1:

**Comment by Torkiwi** [comment]
Now that i'm aware of the mechanic, i'm happy it doesn't override options and it does seems like the right behaviour. ( Its similar to what the standart DS does from what i've read ).

Thanks for the details and the added explanation !
